### ISSUE TITLE
[RFC] Update storage model for streaming refresh

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-design#35]
## Problem

Currently the `Storage` model tries to represent a virtual infra datastore and the underlying physical storage in one record.  This has led to a number of issues, including:

1. Storages can be shared across providers, this means a number of shared properties (i.e. name, ems_ref) will be overwritten by each providers' refresh.  This forced us to add an `:ems_ref` to `HostStorage` for provisioning.
This is really the `:ems_ref` of the datastore in that host's datacenter.  This also means that we cannot practically add other properties to `Storage` like `maintenance_mode` because two providers might have the same storage, one in maintenance mode and one not.

2.  For streaming refresh we must be able to atomically create a skeletal record with only the properties used to associate two managed objects.
For example on VMware when relating a host or a VM to a datastore, they use the datastore ems_ref, not the location.  This means that we cannot atomically `find_or_build` the storage record that we might not have found yet because we aren't able to get the `:location` from the information given.

## Possible solutions

1. Add ems_id to `Storage` and make `ems_ref` the unique reference
We could still use the `:location` property to get unique storages for purposes of reporting total/free/used storage in a provider.

2. Add an intermediate `Datastore` model which belongs_to ext_management_system and storage, and has an `ems_ref`.  Hosts would `have_many :datastores` and `has_many :storages, :through => :datastores`.

`#1` is the simpler solution but if we have a requirement to track physical storages separately from virtual datastores then we would need `#2`

**Comment by agrare** [comment]
cc @Fryguy @gmcculloug @Ladas

**Comment by Fryguy** [comment]
cc @roliveri who's had some potential designs in the past.

**Comment by Ladas** [comment]
@agrare I think the best would be to have 2.) I think that way we should be able to avoid breaking current reports and pages, that are showing storage info aggregated across providers.

**Comment by agrare** [comment]
@Ladas yeah if we do that we'll need to make some other changes as well, e.g. provisioning should select a datastore not a storage, pretty much any model that currently relates to a storage should relate to a datastore instead (host, vm, storage cluster, storage profile, etc...)

**Comment by agrare** [comment]
Summarizing a chat with @roliveri and @Fryguy:

1. We want what we currently call `Storage` to model a virtual datastore with `:ems_ref` being the unique reference (instead of location)

2. We should rename the very generic `Storage` model to `Datastore` to free up the `Storage` name so that we can model actual physical storage providers like Gluster or NetApp

3. We want to add a `Backing` to datastore which will allow us to cross-link a `Datastore` to its underlying `Storage` device.  This backing will container a reference to what the datastore is connected to (e.g.: NFS export, SCSI LUN ID, etc...) which can be discovered by the physical storage inventory refresh.

**Comment by Ladas** [comment]
@agrare I wonder if we could keep all the relations to Storage (so the logic based on that in reports, etc. doesn't have to change) and the datastore would be there just for tracking ems specific attributes and the ems->storages relation?

**Comment by mfeifer** [comment]
Close per @agrare
