### ISSUE TITLE
[RFC] v2v

### ISSUE THREAD

**Issue by bzwei** [ManageIQ/manageiq-design#36]
# Overview
The goal of v2v project is to migrate large quantities of VMs from one provider to another. Selected VMs that need to be migrated are put into a migration plan. For each VM how its resources (cluster, storage, and network) should be migrated from source to destination is not directly configured in the plan. Instead the mapping rule is looked up from a preconfigured mapping set.

There are two personas involved in the v2v workflow. An application admin owns the VMs. He can only select VMs to be migrated but not select where to migrate them because he does not own the infrastructure. An infrastructure admin instead should create the set of mapping rules for resources (cluster, storage, and network) from source to destination.  

# Requirement
An infrastructure admin can create a migration infrastructure mapping. Each mapping has a name, description, and comments. Each mapping contains many mapping item. Each mapping items defines an association of one resource (cluster, storage, or network) from source provider to destination provider. The infrastructure mapping needs to be stored in database and with proper model. RBAC control is required.

In each mapping, source cannot have duplicates but destination can. It allows many sources to one destination association.

Multiple mappings are allowed. A source resource can appear in different mappings but to different destinations.

An application admin can create a migration plan that selects multiple VMs and one mapping. The admin cannot select for each VM how to migrate its resources (cluster, storage, and network). Such source to destination association should be looked up from the selected mapping rule. The plan can have also pre and post playbooks. The plan needs to be stored in database and with proper model. RBAC control is required. The plan can be scheduled to execute in certain time window. 

In each migration plan the selected mapping must be able to provide mapping rules for all resources used by each VM in the plan. A plan cannot be created if no qualified mapping exists. If there more more than one qualified mappings the user has to select only one. 
 
Multiple plans are allowed, but one VM can be selected in only one plan.

The goal of v2v project is to migrate large quantities of VMs from one provider to another. An infrastructure admin will create a resource mapping that maps from source network and storage to destination network and storage. For each mapping only many sources to one destination is allowed.

# Solution
## New table for migration infrastructure mapping 
Table name: `transformation_mappings`
Schema
```
name: string
description: string
comments: string
state: string
tenant_id: integer
created_at: timestamp
updated_at: timestamp
```

## New table for mapping item
Table name: `transformation_mapping_items`
Schema
```
source_id: integer
source_type: string
destination_id: integer
destination_type: string
transformation_mapping_id: integer
options: jsonb
created_at: timestamp
updated_at: timestamp
```
Each `TransformationMapping` can have many `transformation_mapping_items`. Each `TransformationMappingItem` can belong to only one `transformation_mapping`.

## Migration plan
The migration plan can be saved in existing table `service_templates` with a new type `ServiceTemplateV2v`. A new such class inherited from `ServiceTemplate` will be created. Pre and post playbooks can be stored as service_resources. Each selected VM will also be added as a service_resource. Since we need to store additional options for each VM migration and track the migration status two columns are to be added to table `service_resources`

A VM can be only added to one plan.

### Add two columns to `service_resources`
Schema
```
options: jsonb
status: string
```

**Comment by bzwei** [comment]
@Fryguy @gmcculloug

**Comment by bzwei** [comment]
@evenit @pemcg

**Comment by Fryguy** [comment]
Initial comments:

- make mapping_items to a specific table named v2v_mapping_items and change it from polymorphic to a normal belongs_to
- what is `status`...way too generic name... @bzwei I think from our direct conversation you mean `state`.

- For the v2v_mapping_items, what will happen if the source or destination is deleted.  e.g. someone deletes a network or a disk that was part of a mapping.  Should we alert the user ahead of time or wait until run time (runtime might be really bad if they schedule a weekend to do this and suddenly it stops working in the middle)?  Should we prevent deletion of a resource if it's tied to a mapping?  If so, what happens it's deleted at the provider natively?

This is missing A LOT of details around the v2v implementation, such as models, how it will work, what the state machine will look like, how scheduling will work, use cases, edge conditions, etc.  Need much more info.

**Comment by bzwei** [comment]
updated the schema based on the above comments

**Comment by bthurber** [comment]
This can be closed as we have completed development past this point for v2v.
