### ISSUE TITLE
[RFC] Common way to describe Physical Components

### ISSUE THREAD

**Issue by douglasgabriel** [ManageIQ/manageiq-design#42]
Problem
===

In ManageIQ there isn't a common way to describe all physical components that a Physical Infra Manager can manage, so that, we are not able to share common routines or relationships between every component.

### The Physical Components

Today we have the following physical components:

- Physical Server;
- Physical Switch;
- Physical Chassis;
- Physical Storage;
- Physical Rack;

### Common relationships

We can notice some relationships common to every physical component

- `has_one :asset_detail`
- `has_one :hardware`

*Among others...*

### Common routines

**Find physical connections**: Every Physical Component may have physical network ports, that can be connected to another physical component, so, the routine to bring the connected components can be shared with every physical component in this common class.

**Hardware resources**: This entity could have information of the total of CPUs, Storage, Memory etc, making the computation of these data more easy for a Physical Infra Manager scope once it will be centralized in just one table.

*Among others...*

### About computer_system

The entity that looks more like what we are looking for is `computer_system`, once that it is a polymorphic entity that sets many of common relationships that do works for Physical Components. 

But, what is generating doubts about using this entity is that just one physical component, semantically, is a "computer system", which is physical servers, besides that, shared routines that live in this entity are shared with `ContainerImage`, as well, which doesn't seem right.

### Solutions

1) Ignore the fact that some components are not a "Computer System", add this relationship to every component and use it to share routines and relationships;

1) Create a new polymorphic entity called `physical_component`, relate every physical component to it and win a new place to share stuff between these entities. 

Beside that, `physical_server` would keep it relationship with `computer_system` once it make sense. But, for those relationships that coexists in `physical_component` and `computer_system` the `physical_component` way should be prioritized.

![image](https://user-images.githubusercontent.com/8550928/42758245-42df34f8-88d9-11e8-9fa6-5237bcafa4a5.png)

/cc
@Fryguy
@agrare
@gtanzillo
@rodneyhbrown7
@caiocmpaes
@saulotoledo

**Comment by caiocmpaes** [comment]
@douglasgabriel I liked your description of the problem. That diagram helped a lot. For me, the 2nd approach makes more sense.

**Comment by douglasgabriel** [comment]
Discussed with @agrare, @gtanzillo, @caiocmpaes and @rodneyhbrown7 and we decided to go forward with the first solution:

> Ignore the fact that some components are not a "Computer System", add this relationship to every component and use it to share routines and relationships;

Additionally, if the `hardware` entity fits all the needs of some "Physical Component" so we can make this entity polymorphic and add a direct relationship to it.
